<a href="https://colab.research.google.com/github/gsangf10/numpy/blob/main/numpy_%EB%AC%B8%EC%A0%9C_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

li = [[1880, 90993, 110491],
[1881, 91954, 100745],
[1882, 107850, 113688],
[1883, 112321, 104629],
[1884, 129022, 114445],
[1885, 133055, 107800],
[1886, 144535, 110784],
[1887, 145982, 101414],
[1888, 178627, 120853],
[1889, 178366, 110584],
[1890, 190377, 111025],
[1891, 185482, 101196],
[1892, 212346, 122037],
[1893, 212906, 112317],
[1894, 222922, 115772],
[1895, 233630, 117398],
[1896, 237920, 119570],
[1897, 234202, 112758],
[1898, 258770, 122693],
[1899, 233023, 106212],
[1900, 299828, 150499],
[1901, 239348, 106471],
[1902, 264077, 122659],
[1903, 261973, 119234],
[1904, 275371, 128125],
[1905, 291629, 132319],
[1906, 295303, 133159],
[1907, 318566, 146833],
[1908, 334313, 154344],
[1909, 347228, 163999],
[1910, 396501, 194218],
[1911, 418299, 225968],
[1912, 558103, 429945],
[1913, 624518, 512557],
[1914, 761548, 654762],
[1915, 983874, 848603],
[1916, 1044323, 890099],
[1917, 1081280, 925511],
[1918, 1157647, 1013537],
[1919, 1130145, 980149],
[1920, 1198283, 1064463],
[1921, 1232999, 1101457],
[1922, 1200919, 1088287],
[1923, 1206330, 1096168],
[1924, 1248876, 1132751],
[1925, 1217352, 1115958],
[1926, 1185304, 1110505],
[1927, 1192330, 1126717],
[1928, 1153117, 1107518],
[1929, 1116422, 1075313],
[1930, 1125761, 1097176],
[1931, 1064497, 1039127],
[1932, 1066994, 1043808],
[1933, 1007710, 991127],
[1934, 1044039, 1032291],
[1935, 1048428, 1040930],
[1936, 1040202, 1036974],
[1937, 1063872, 1066309],
[1938, 1103277, 1108841],
[1939, 1096518, 1106544],
[1940, 1143325, 1158900],
[1941, 1207919, 1227941],
[1942, 1350545, 1380774],
[1943, 1395082, 1426846],
[1944, 1327104, 1362555],
[1945, 1307028, 1345610],
[1946, 1571184, 1623650],
[1947, 1772644, 1829223],
[1948, 1697814, 1754469],
[1949, 1710825, 1773725],
[1950, 1713180, 1790673],
[1951, 1800042, 1881080],
[1952, 1854698, 1944277],
[1953, 1880326, 1969777],
[1954, 1941682, 2037374],
[1955, 1954664, 2057918],
[1956, 2007512, 2113694],
[1957, 2044160, 2155866],
[1958, 2010884, 2120712],
[1959, 2023044, 2133509],
[1960, 2022093, 2132717],
[1961, 2017316, 2122502],
[1962, 1966548, 2068945],
[1963, 1927217, 2031755],
[1964, 1894594, 1993270],
[1965, 1765001, 1861378],
[1966, 1691868, 1783964],
[1967, 1650764, 1744527],
[1968, 1640103, 1738928],
[1969, 1686947, 1789732],
[1970, 1748147, 1859594],
[1971, 1663475, 1769201],
[1972, 1521185, 1622666],
[1973, 1458139, 1559338],
[1974, 1467413, 1573105],
[1975, 1457699, 1562207],
[1976, 1465096, 1569904],
[1977, 1532997, 1643684],
[1978, 1531658, 1642250],
[1979, 1605051, 1721947],
[1980, 1659933, 1783876],
[1981, 1667465, 1790907],
[1982, 1692678, 1813970],
[1983, 1670061, 1791732],
[1984, 1682973, 1803830],
[1985, 1720036, 1847032],
[1986, 1714664, 1840164],
[1987, 1737891, 1865662],
[1988, 1779839, 1912602],
[1989, 1843105, 1999999],
[1990, 1897709, 2052543],
[1991, 1874434, 2019463],
[1992, 1843304, 1996388],
[1993, 1808379, 1960397],
[1994, 1785074, 1931157],
[1995, 1757927, 1902832],
[1996, 1752249, 1893378],
[1997, 1739806, 1884122],
[1998, 1765915, 1910250],
[1999, 1772632, 1918809],
[2000, 1814601, 1962406],
[2001, 1799049, 1941251],
[2002, 1795206, 1939815],
[2003, 1825359, 1973434],
[2004, 1834145, 1982794],
[2005, 1845379, 1994841],
[2006, 1898463, 2052377],
[2007, 1919408, 2072139],
[2008, 1887234, 2036289],
[2009, 1832925, 1979303],
[2010, 1772738, 1913851],
[2011, 1753500, 1893230]]


In [ ]:
# 남자 출생이 가장 많은 top5 (연도와 남아수)
arr = np.array(li)
idx = arr[:, 1].argsort()[::-1]
arr2 = arr[idx]
arr2[:5,:2]


array([[   1957, 2044160],
       [   1959, 2023044],
       [   1960, 2022093],
       [   1961, 2017316],
       [   1958, 2010884]])

In [ ]:
# 남아 여아 남아율 

# 남아 + 여아 / 남아

arr[:, 1:3]
arr1 = arr[:, 1:2] / (arr[:, 1:2] + arr[:, 2:3]) * 100
arr2 = arr[:, 1:3]
arr3 = np.concatenate((arr2, arr1), axis=1)

# 형변환
arr3.astype('str')


array([['90993.0', '110491.0', '45.16140239423478'],
       ['91954.0', '100745.0', '47.718981416613474'],
       ['107850.0', '113688.0', '48.68239308831893'],
       ['112321.0', '104629.0', '51.772758700161326'],
       ['129022.0', '114445.0', '52.99362952679418'],
       ['133055.0', '107800.0', '55.24278092628345'],
       ['144535.0', '110784.0', '56.60957468891857'],
       ['145982.0', '101414.0', '59.00742130026354'],
       ['178627.0', '120853.0', '59.64571924669427'],
       ['178366.0', '110584.0', '61.7290188613947'],
       ['190377.0', '111025.0', '63.16381444051466'],
       ['185482.0', '101196.0', '64.70046533044042'],
       ['212346.0', '122037.0', '63.50382645050735'],
       ['212906.0', '112317.0', '65.4646196609711'],
       ['222922.0', '115772.0', '65.81811310504467'],
       ['233630.0', '117398.0', '66.55594425515913'],
       ['237920.0', '119570.0', '66.55291057092506'],
       ['234202.0', '112758.0', '67.50115287064791'],
       ['258770.0', '122693.0'

In [ ]:
# 2000년대 이후 출생량, 남아수 1800000 이상이면 많음 아니면 적음

arr2 = arr[arr[:, 0] >= 2000]

flags = []

for row in arr2:
  flag = "적음"

  if row[1] >= 1800000 :
    flag = "많음"

  flags.append(flag)

arr3 = np.array(flags)

print(arr2)
print(arr3)

arr3 = np.expand_dims(arr3, axis=1)
np.concatenate((arr2, arr3), axis=1)


[[   2000 1814601 1962406]
 [   2001 1799049 1941251]
 [   2002 1795206 1939815]
 [   2003 1825359 1973434]
 [   2004 1834145 1982794]
 [   2005 1845379 1994841]
 [   2006 1898463 2052377]
 [   2007 1919408 2072139]
 [   2008 1887234 2036289]
 [   2009 1832925 1979303]
 [   2010 1772738 1913851]
 [   2011 1753500 1893230]]
['많음' '적음' '적음' '많음' '많음' '많음' '많음' '많음' '많음' '많음' '적음' '적음']


array([['2000', '1814601', '1962406', '많음'],
       ['2001', '1799049', '1941251', '적음'],
       ['2002', '1795206', '1939815', '적음'],
       ['2003', '1825359', '1973434', '많음'],
       ['2004', '1834145', '1982794', '많음'],
       ['2005', '1845379', '1994841', '많음'],
       ['2006', '1898463', '2052377', '많음'],
       ['2007', '1919408', '2072139', '많음'],
       ['2008', '1887234', '2036289', '많음'],
       ['2009', '1832925', '1979303', '많음'],
       ['2010', '1772738', '1913851', '적음'],
       ['2011', '1753500', '1893230', '적음']], dtype='<U21')

In [ ]:
# 여아 25% ~ 75% 사이의 값

# 25% 위치에 있는 인덱스
# 75% 위치에 있는 인덱스

idx25 = 132 * 0.25 - 1 
idx25 = int(idx25)

idx75 = 132 * 0.75 - 1
idx75 = int(idx75)

arr2 = np.sort(arr[:, 2])
arr3 = arr2[arr2 >= arr2[idx25]]

arr3[arr3 <= arr2[idx75]]

 

array([ 429945,  512557,  654762,  848603,  890099,  925511,  980149,
        991127, 1013537, 1032291, 1036974, 1039127, 1040930, 1043808,
       1064463, 1066309, 1075313, 1088287, 1096168, 1097176, 1101457,
       1106544, 1107518, 1108841, 1110505, 1115958, 1126717, 1132751,
       1158900, 1227941, 1345610, 1362555, 1380774, 1426846, 1559338,
       1562207, 1569904, 1573105, 1622666, 1623650, 1642250, 1643684,
       1721947, 1738928, 1744527, 1754469, 1769201, 1773725, 1783876,
       1783964, 1789732, 1790673, 1790907, 1791732, 1803830, 1813970,
       1829223, 1840164, 1847032, 1859594, 1861378, 1865662, 1881080,
       1884122, 1893230, 1893378, 1902832])